server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.5.201:3306/coca?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.5.202 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456pq # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    elasticsearch:
      repositories:
        enabled: true
    cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
    cluster-name: elasticsearch # es集群的名

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml



